### ISSUE TITLE
Audio not working

### ISSUE THREAD

**Issue by cAstraea** [pixhub/Desktop-Streaming-ffmpeg#1]
Hello been trying to get this working but no luck I'm running it on a digital ocean.

the ffmpeg -f alsa -ac 2 -i pulse -acodec libmp3lame -ab 128k testfile.mp3 sounds records
tried to combine it with 
`ffmpeg -f x11grab -s 1024x768 -r 30 -i $DISPLAY -f alsa -ac 2 -i pulse -acodec libmp3lame -ab 128k -vcodec libx264 myvideo.mpg `

to record chrome window playing a video but myvideo.mpg only has audio for few seconds ? 

[x11grab @ 0x55ba9319c0e0] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)

[mpeg @ 0x55ba931c0b40] Non-monotonous DTS in output stream 0:1; previous: 186245, current: 174176; changing to 186246. This may result in incorrect timestamps in the output file.
 
What does this even mean ?

**Comment by pixhub** [comment]
Hi,

Sorry, this repo is a little bit old, and not really updated.
Try this instead if you wanna make a video :

ffmpeg -s 1024x768 -r 30 -f x11grab -i $DISPLAY -f pulse -ac 2 -i default myvideo.mpg



2018-01-08 10:01 GMT+01:00 cAstraea <notifications@github.com>:

**Comment by pixhub** [comment]
I close the issue.
Feel free to re-open it.

Best regards,
pixhub.

**Comment by cAstraea** [comment]
Thank you ! :)
Think it's working a bit better now , this is what I'm using to stream to HLS. Found some guides that said to install some ngxing rtmp module. No idea why that is needed ? Seems ffmpeg can do this conversion also.
[ ffmpeg -thread_queue_size 3048 -f pulse -ac 2 -i default -c:a aac -f x11grab -s 1000x564 -r 30 -i $DISPLAY+10,151 -vcodec libx264 -preset ultrafast -maxrate 2M -bufsize 300k -g 30 -movflags +faststart -tune zerolatency -x264opts keyint=30:min-keyint=10:no-scenecut -b:v 1000k -s 1000x562 -pix_fmt yuv420p -b:a 96k -ar 44100 -threads 0 -hls_list_size 0 -start_number 0 -hls_allow_cache 0 -hls_init_time 2 -hls_time 10 -hls_wrap 7 /usr/local/nginx/html/testlist.m3u8 2> /home/ubuntu/HLS_STREAM_LOG$$.log ](url)

**Comment by pixhub** [comment]
Ok. If you want, try my WIKI about HLS (here: https://github.com/pixhub/Desktop-Streaming-ffmpeg/wiki/Page-4-Stream-your-Desktop-in-HLS-and-watch-it-in-a-web-page)
Also, if you use to play with Docker, i made a Docker image whicj embed a Flow Play in a WebPage ready-to-use (here: https://github.com/pixhub/docker_nginx-rtmp)

You also can pull the Docker image by : docker pull pixhub/docker_nginx-rtmp
see : https://hub.docker.com/r/pixhub/docker_nginx-rtmp/

You will also find a ffmpeg script with option, making it easily to stream.

I hope you'll enjoy that.

Best regards,
pixhub.
